apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - observability/kube-prometheus-stack.yaml
  - observability/prometheus-community-source.yaml
# - gotk-components.yaml
# - gotk-sync.yaml
